repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: detect-private-key
    -   id: check-ast
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-symlinks
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
